name: REMLA-project
on:
 push:

permissions:
  actions: write
  checks: write
  contents: write

jobs:
  static-checks:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: build environment
      run: make requirements
    - name: check black
      if: always()
      run: make check-black
    - name: check isort
      if: always()
      run: make check-isort
    - name: check flake8
      if: always()
      run: make check-flake8
    - name: check bandit
      if: always()
      run: make check-bandit
    - name: check mllint
      if: always()
      run: make check-mllint
    - name: upload mllint report
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: mllint-report
        path: reports/mllint_report.md
    - name: Create CheckRun for code Coverage
      uses: LouisBrunner/checks-action@v1.2.0
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Code Coverage
        conclusion: ${{ job.status }}
        output: "{\"summary\":\"mllint report\"}"
        output_text_description_file: reports/mllint_report.md