name: REMLA-project
on:
 push:

jobs:
  static-checks:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name Set up python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: build environment
      run: make requirements
    - name: static checks
      run: make static-checks