name: REMLA-project
on:
 push:

jobs:
  static-checks:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: build environment
      run: make requirements
    - name: check black
      if: always()
      run: make check-black
    - name: check isort
      if: always()
      run: make check-isort
    - name: check flake8
      if: always()
      run: make check-flake8
    - name: check bandit
      if: always()
      run: make check-bandit
    - name: check mllint
      if: always()
      id: mllint
      run: make check-mllint
    - name: test
      if: always()
      run: |
        echo "success"
    - name: test mllint outcom
      if: steps.mllint.outcome == 'success'
      run: |
        echo "success"
    - name: upload mllint report
      uses: actions/upload-artifact@v2
      if: steps.mllint.outcome == 'success'
      with:
        name: mllint-report
        path: reports/mllint_report.md
